package com.mycompany.myapp;


import GUI.HomeForm;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Display;
import com.codename1.ui.Toolbar;
import com.codename1.uikit.materialscreens.LoginForm;
import com.codename1.uikit.materialscreens.WalkthruForm;


/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
//        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme_1");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(false);

        // Pro only feature
       
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        new LoginForm(theme).show();
//        HomeForm h = new HomeForm();
//        h.getF().show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
